lesson3
soulfly2007/homework pull request #1
Opened 2023-06-23 15:15 UTC by soulfly2007

2023-07-05 14:03 UTC, a-kosak-mbx requested changes
Нужно исправить ошибки.

2023-07-05 14:03 UTC, a-kosak-mbx commented on homework/lesson3.py
> +s = ''.join(a for a in s if a not in punctuation)
А что с дефисами и хэштэгами?

2023-07-05 14:03 UTC, a-kosak-mbx commented on homework/lesson3.py
> +    if i not in s1:
Сложность поиска в строке линейная. В результате сложность всего алгоритма выходит квадратичной. Попробуйте упростить алгоритм.

2023-07-06 08:08 UTC, soulfly2007 commented on homework/lesson3.py
> +s = ''.join(a for a in s if a not in punctuation)
Так 'punctuation' включает дефис и хэштэг. 'punctuation' = !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

2023-07-16 13:38 UTC, a-kosak-mbx requested changes
Нужны исправления.

2023-07-16 13:38 UTC, a-kosak-mbx commented on homework/lesson3.py
> +s = ''.join(a for a in s if a not in punctuation)
В этом и суть. Они есть, но `#котяточки` - слово, как и `по-кошачьи`.

2023-07-16 15:56 UTC, soulfly2007 commented on homework/lesson3.py
> +s = ''.join(a for a in s if a not in punctuation)
Теперь понятно. Буду просто исключать знаки препинания.

2023-08-24 21:14 UTC, a-kosak-mbx approved these changes

2023-08-24 21:16 UTC, a-kosak-mbx requested changes

2023-08-24 21:16 UTC, a-kosak-mbx commented on homework/lesson3.py
> +s = ''.join(sorted(set(s.replace(' ', ''))))
Не будет работать. Нужно использовать дикт вместо сэт.

2023-09-03 09:34 UTC, a-kosak-mbx approved these changes

2023-09-09 08:16 UTC, merged